name: 'Prepare Rust'
description: 'Sets up rust'
inputs:
  rust_components:
    description: 'Rust components to install'
    required: false
    default: 'rustfmt, clippy'
runs:
  using: "composite"
  steps:
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e
        with:
          toolchain: stable
          components: ${{ inputs.rust_components }}
