[package]
name = "status-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-process = "1.7.0"
log = "0.4.19"
rocket = "=0.5.0-rc.3"
rocket-governor = "0.1.0-rc.4"
