[default]
probe_reqs_per_min=1

[default.probes.hostname]
command = "hostname"
args = []

[windows.probes.version]
command = "cmd"
args = ["/c", "ver"]

[linux.probes.version]
command = "uname"
args = []
